/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/9.glb')
  const { actions } = useAnimations(animations, group)

 
 console.log("hola", actions)

  useFrame(() => {
    actions.down.play()
  })
 

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[0, 4.523, 0]}
        />
      </group>
    </group>
  )
}
