/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef, useImperativeHandle } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import * as THREE from 'three'


// forwardRef permite que el padre reciba un ref 
const Model = forwardRef(({ materialConfig, color = 'white', ...props }, ref) => {

  const group = useRef()

  const { nodes, materials, animations } = useGLTF('/models/wallet2.1.glb')
  const { actions } = useAnimations(animations, group)

  // 👇 AQUÍ expones las animaciones
  // Cuando alguien use el ref de este componente, le voy a dar acceso a actions.
  useImperativeHandle(ref, () => ({
    actions,
    group
  }))

  const textures = useTexture(materialConfig)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature-plastic">
          <skinnedMesh
            name="plastic-piece"
            geometry={nodes['plastic-piece'].geometry}
            material={nodes['plastic-piece'].material}
            skeleton={nodes['plastic-piece'].skeleton}
          />
          <primitive object={nodes['bb-1']} />
          <primitive object={nodes['bb-2']} />
        </group>
        <group name="Armature-leather">
          <skinnedMesh
            name="costuras"
            geometry={nodes.costuras.geometry}
            material={nodes.costuras.material}
            skeleton={nodes.costuras.skeleton}
          />
          <skinnedMesh
            name="leather-piece"
            geometry={nodes['leather-piece'].geometry}
            skeleton={nodes['leather-piece'].skeleton}
          >
            <meshStandardMaterial 
              map={textures.map}
              normalMap={textures.normalMap}
            />
          </skinnedMesh>
          
          <primitive object={nodes['bc-1']} />
        </group>
        <mesh
          name="metal-piece"
          castShadow
          receiveShadow
          geometry={nodes['metal-piece'].geometry}
          material={nodes['metal-piece'].material}
        />
      </group>
    </group>
  )
})

export default Model




          // <skinnedMesh
          //   name="leather-piece"
          //   geometry={nodes['leather-piece'].geometry}
          //   skeleton={nodes['leather-piece'].skeleton}
          // >
          //   <meshStandardMaterial
          //     map={textures.map}
          //     normalMap={textures.normalMap}
          //   />
          // </skinnedMesh>